# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: contact@baselinehq.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricing_api_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_healthz_get(self) -> None:
        """Test case for healthz_get

        Health check endpoint
        """
        pass

    def test_marketplace_providers_compute_delete(self) -> None:
        """Test case for marketplace_providers_compute_delete

        Delete a custom provider instance
        """
        pass

    def test_marketplace_providers_compute_get(self) -> None:
        """Test case for marketplace_providers_compute_get

        Get your custom pricing entries
        """
        pass

    def test_marketplace_providers_compute_post(self) -> None:
        """Test case for marketplace_providers_compute_post

        Register a custom provider
        """
        pass

    def test_pricing_compute_post(self) -> None:
        """Test case for pricing_compute_post

        Get  pricing for an instance
        """
        pass

    def test_pricing_disks_post(self) -> None:
        """Test case for pricing_disks_post

        Get  pricing for a disk
        """
        pass

    def test_providers_get(self) -> None:
        """Test case for providers_get

        Get details for the providers
        """
        pass

    def test_recommendations_compute_post(self) -> None:
        """Test case for recommendations_compute_post

        Get recommendations for compute instances
        """
        pass

    def test_recommendations_disks_post(self) -> None:
        """Test case for recommendations_disks_post

        Get recommendations for disks
        """
        pass


if __name__ == '__main__':
    unittest.main()
