# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: support@costgraph.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricing_api_client.models.disk_recommendation_request import DiskRecommendationRequest

class TestDiskRecommendationRequest(unittest.TestCase):
    """DiskRecommendationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DiskRecommendationRequest:
        """Test DiskRecommendationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DiskRecommendationRequest`
        """
        model = DiskRecommendationRequest()
        if include_optional:
            return DiskRecommendationRequest(
                include_metadata = True,
                instance = pricing_api_client.models.types/disk.types.Disk(
                    availability_zone = '', 
                    capacity_gb = 1.337, 
                    fallback_to_base_pricing = True, 
                    id = '', 
                    iops = 1.337, 
                    provider = 'GCP', 
                    region = '', 
                    service = 'ComputeEngine', 
                    throughput_mbps = 1.337, 
                    type = '', 
                    usage_type = 'SPOT_PREEMPTIBLE', ),
                predicates = pricing_api_client.models.types/predicates.types.Predicates(
                    availability_zones = [
                        ''
                        ], 
                    disk_types = [
                        ''
                        ], 
                    instance_types = [
                        ''
                        ], 
                    operating_systems = [
                        ''
                        ], 
                    providers = [
                        ''
                        ], 
                    regions = [
                        ''
                        ], 
                    services = [
                        ''
                        ], 
                    usage_types = [
                        ''
                        ], ),
                usage = pricing_api_client.models.types/disk.types.Disk(
                    availability_zone = '', 
                    capacity_gb = 1.337, 
                    fallback_to_base_pricing = True, 
                    id = '', 
                    iops = 1.337, 
                    provider = 'GCP', 
                    region = '', 
                    service = 'ComputeEngine', 
                    throughput_mbps = 1.337, 
                    type = '', 
                    usage_type = 'SPOT_PREEMPTIBLE', )
            )
        else:
            return DiskRecommendationRequest(
        )
        """

    def testDiskRecommendationRequest(self):
        """Test DiskRecommendationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
