# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: support@costgraph.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricing_api_client.models.model_price import ModelPrice

class TestModelPrice(unittest.TestCase):
    """ModelPrice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelPrice:
        """Test ModelPrice
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelPrice`
        """
        model = ModelPrice()
        if include_optional:
            return ModelPrice(
                context_limit = 56,
                currency = '',
                effective_from = '',
                effective_to = '',
                fetched_at = '',
                host = '',
                id = '',
                modalities_input = [
                    ''
                    ],
                modalities_output = [
                    ''
                    ],
                model = '',
                model_id = '',
                open_weights = True,
                output_limit = 56,
                provider = '',
                publisher = '',
                raw_pricing_data = None,
                reasoning = True,
                region = '',
                sku_price_id = '',
                source = '',
                source_url = '',
                structured_output = True,
                tags = None,
                token_bucket = '',
                tool_call = True,
                unit_price_per_mtok = 1.337
            )
        else:
            return ModelPrice(
        )
        """

    def testModelPrice(self):
        """Test ModelPrice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
