# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: support@costgraph.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricing_api_client.models.types_service import TypesService

class TestTypesService(unittest.TestCase):
    """TypesService unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTypesService(self):
        """Test TypesService"""
        # inst = TypesService()

if __name__ == '__main__':
    unittest.main()
