# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: support@costgraph.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricing_api_client.api.service_api import ServiceApi


class TestServiceApi(unittest.TestCase):
    """ServiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServiceApi()

    def tearDown(self) -> None:
        pass

    def test_v1_healthz_get(self) -> None:
        """Test case for v1_healthz_get

        Check the service is live
        """
        pass


if __name__ == '__main__':
    unittest.main()
