# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: support@costgraph.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricing_api_client.models.registered_disk_prices import RegisteredDiskPrices

class TestRegisteredDiskPrices(unittest.TestCase):
    """RegisteredDiskPrices unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RegisteredDiskPrices:
        """Test RegisteredDiskPrices
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RegisteredDiskPrices`
        """
        model = RegisteredDiskPrices()
        if include_optional:
            return RegisteredDiskPrices(
                entries = [
                    pricing_api_client.models.disk_price.DiskPrice(
                        availability_zone = '', 
                        cost_per_gb_hour = 1.337, 
                        cost_per_iops_hour = 1.337, 
                        cost_per_throughput_mbps_hour = 1.337, 
                        created_at = '', 
                        currency = '', 
                        id = '', 
                        max_capacity_gb = 1.337, 
                        max_iops = 1.337, 
                        max_throughput_mbps = 1.337, 
                        min_capacity_gb = 1.337, 
                        min_iops = 1.337, 
                        min_throughput_mbps = 1.337, 
                        native_cost_per_gb_hour = 1.337, 
                        native_cost_per_iops_hour = 1.337, 
                        native_cost_per_throughput_mbps_hour = 1.337, 
                        period_billing_hours = 1.337, 
                        provider = '', 
                        raw_pricing_data = pricing_api_client.models.raw_pricing_data.raw_pricing_data(), 
                        region = '', 
                        service = '', 
                        tags = pricing_api_client.models.tags.tags(), 
                        type = '', 
                        updated_at = '', 
                        usage_type = '', )
                    ],
                status = 'Registered'
            )
        else:
            return RegisteredDiskPrices(
        )
        """

    def testRegisteredDiskPrices(self):
        """Test RegisteredDiskPrices"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
