# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: support@costgraph.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricing_api_client.api.pricing_api import PricingApi


class TestPricingApi(unittest.TestCase):
    """PricingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PricingApi()

    def tearDown(self) -> None:
        pass

    def test_v1_pricing_compute_post(self) -> None:
        """Test case for v1_pricing_compute_post

        Price a machine
        """
        pass

    def test_v1_pricing_disks_post(self) -> None:
        """Test case for v1_pricing_disks_post

        Price a volume
        """
        pass


if __name__ == '__main__':
    unittest.main()
