# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: support@costgraph.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricing_api_client.models.registered_model_prices import RegisteredModelPrices

class TestRegisteredModelPrices(unittest.TestCase):
    """RegisteredModelPrices unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RegisteredModelPrices:
        """Test RegisteredModelPrices
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RegisteredModelPrices`
        """
        model = RegisteredModelPrices()
        if include_optional:
            return RegisteredModelPrices(
                entries = [
                    pricing_api_client.models.model_price.ModelPrice(
                        context_limit = 56, 
                        currency = '', 
                        effective_from = '', 
                        effective_to = '', 
                        fetched_at = '', 
                        host = '', 
                        id = '', 
                        modalities_input = [
                            ''
                            ], 
                        modalities_output = [
                            ''
                            ], 
                        model = '', 
                        model_id = '', 
                        open_weights = True, 
                        output_limit = 56, 
                        provider = '', 
                        publisher = '', 
                        raw_pricing_data = pricing_api_client.models.raw_pricing_data.raw_pricing_data(), 
                        reasoning = True, 
                        region = '', 
                        sku_price_id = '', 
                        source = '', 
                        source_url = '', 
                        structured_output = True, 
                        tags = pricing_api_client.models.raw_pricing_data.raw_pricing_data(), 
                        token_bucket = '', 
                        tool_call = True, 
                        unit_price_per_mtok = 1.337, )
                    ],
                status = 'Registered'
            )
        else:
            return RegisteredModelPrices(
        )
        """

    def testRegisteredModelPrices(self):
        """Test RegisteredModelPrices"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
