# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: support@costgraph.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricing_api_client.api.recommendations_api import RecommendationsApi


class TestRecommendationsApi(unittest.TestCase):
    """RecommendationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RecommendationsApi()

    def tearDown(self) -> None:
        pass

    def test_v1_recommendations_compute_post(self) -> None:
        """Test case for v1_recommendations_compute_post

        Find cheaper machines
        """
        pass

    def test_v1_recommendations_disks_post(self) -> None:
        """Test case for v1_recommendations_disks_post

        Find cheaper volumes
        """
        pass


if __name__ == '__main__':
    unittest.main()
