# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: contact@baselinehq.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricing_api_client.models.github_com_baselinehq_pricingapi_pkg_types_status import GithubComBaselinehqPricingapiPkgTypesStatus

class TestGithubComBaselinehqPricingapiPkgTypesStatus(unittest.TestCase):
    """GithubComBaselinehqPricingapiPkgTypesStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGithubComBaselinehqPricingapiPkgTypesStatus(self):
        """Test GithubComBaselinehqPricingapiPkgTypesStatus"""
        # inst = GithubComBaselinehqPricingapiPkgTypesStatus()

if __name__ == '__main__':
    unittest.main()
