# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: support@costgraph.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricing_api_client.models.registered_database_prices import RegisteredDatabasePrices

class TestRegisteredDatabasePrices(unittest.TestCase):
    """RegisteredDatabasePrices unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RegisteredDatabasePrices:
        """Test RegisteredDatabasePrices
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RegisteredDatabasePrices`
        """
        model = RegisteredDatabasePrices()
        if include_optional:
            return RegisteredDatabasePrices(
                entries = [
                    pricing_api_client.models.database_price.DatabasePrice(
                        architecture = '', 
                        availability_zone = '', 
                        billing_config = '', 
                        capacity_unit = '', 
                        cost_per_capacity_unit = 1.337, 
                        cost_per_hour = 1.337, 
                        cost_per_io_request = 1.337, 
                        cost_per_iops_hour = 1.337, 
                        cost_per_storage_gb_hour = 1.337, 
                        cost_per_throughput_mbps_hour = 1.337, 
                        cost_per_vcpu_license_hour = 1.337, 
                        cpu_cores = 1.337, 
                        cpu_cores_cost_per_hour = 1.337, 
                        created_at = '', 
                        currency = '', 
                        deployment_option = '', 
                        edition = '', 
                        engine = '', 
                        id = '', 
                        instance_type = '', 
                        max_iops = 1.337, 
                        max_storage_gb = 1.337, 
                        max_throughput_mbps = 1.337, 
                        min_iops = 1.337, 
                        min_storage_gb = 1.337, 
                        min_throughput_mbps = 1.337, 
                        native_cost_per_hour = 1.337, 
                        native_cost_per_storage_gb_hour = 1.337, 
                        period_billing_hours = 1.337, 
                        provider = '', 
                        ram_gb = 1.337, 
                        ram_gb_cost_per_hour = 1.337, 
                        raw_pricing_data = pricing_api_client.models.raw_pricing_data.raw_pricing_data(), 
                        region = '', 
                        service = '', 
                        storage_type = '', 
                        tags = pricing_api_client.models.tags.tags(), 
                        updated_at = '', 
                        usage_type = '', )
                    ],
                status = 'Registered'
            )
        else:
            return RegisteredDatabasePrices(
        )
        """

    def testRegisteredDatabasePrices(self):
        """Test RegisteredDatabasePrices"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
