# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: support@costgraph.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricing_api_client.models.filter_set import FilterSet

class TestFilterSet(unittest.TestCase):
    """FilterSet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FilterSet:
        """Test FilterSet
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FilterSet`
        """
        model = FilterSet()
        if include_optional:
            return FilterSet(
                filters = [
                    ''
                    ],
                kind = ''
            )
        else:
            return FilterSet(
        )
        """

    def testFilterSet(self):
        """Test FilterSet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
