# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: support@costgraph.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricing_api_client.models.published_compute_prices import PublishedComputePrices

class TestPublishedComputePrices(unittest.TestCase):
    """PublishedComputePrices unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublishedComputePrices:
        """Test PublishedComputePrices
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublishedComputePrices`
        """
        model = PublishedComputePrices()
        if include_optional:
            return PublishedComputePrices(
                data = [
                    pricing_api_client.models.compute_price.ComputePrice(
                        architecture = '', 
                        availability_zone = '', 
                        cost_per_hour = 1.337, 
                        cpu_cores = 1.337, 
                        cpu_cores_cost_per_hour = 1.337, 
                        created_at = '', 
                        currency = '', 
                        gpu_cost_per_hour = 1.337, 
                        gpu_count = 1.337, 
                        gpu_type = '', 
                        id = '', 
                        instance_type = '', 
                        native_cost_per_hour = 1.337, 
                        operating_system = '', 
                        period_billing_hours = 1.337, 
                        provider = '', 
                        ram_gb = 1.337, 
                        ram_gb_cost_per_hour = 1.337, 
                        raw_pricing_data = pricing_api_client.models.raw_pricing_data.raw_pricing_data(), 
                        region = '', 
                        service = '', 
                        tags = pricing_api_client.models.tags.tags(), 
                        updated_at = '', 
                        usage_type = '', )
                    ]
            )
        else:
            return PublishedComputePrices(
        )
        """

    def testPublishedComputePrices(self):
        """Test PublishedComputePrices"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
