# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: contact@baselinehq.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricing_api_client.models.types_compute_request import TypesComputeRequest

class TestTypesComputeRequest(unittest.TestCase):
    """TypesComputeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TypesComputeRequest:
        """Test TypesComputeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TypesComputeRequest`
        """
        model = TypesComputeRequest()
        if include_optional:
            return TypesComputeRequest(
                include_metadata = True,
                instance = pricing_api_client.models.github_com_baselinehq_golang_shared_types/instance.github_com_baselinehq_golang-shared_types.Instance(
                    availability_zone = '', 
                    id = '', 
                    instance_type = '', 
                    operating_system = '', 
                    provider = 'GCP', 
                    region = '', 
                    service = 'ComputeEngine', 
                    usage_type = 'SPOT_PREEMPTIBLE', 
                    vm = pricing_api_client.models.github_com_baselinehq_golang_shared_types/vm.github_com_baselinehq_golang-shared_types.VM(
                        cpu_cores = 1.337, 
                        ram_gb = 1.337, ), ),
                predicates = pricing_api_client.models.types/predicates.types.Predicates(
                    availability_zones = [
                        ''
                        ], 
                    disk_types = [
                        ''
                        ], 
                    instance_types = [
                        ''
                        ], 
                    operating_systems = [
                        ''
                        ], 
                    providers = [
                        ''
                        ], 
                    regions = [
                        ''
                        ], 
                    services = [
                        ''
                        ], 
                    usage_types = [
                        ''
                        ], ),
                usage = pricing_api_client.models.github_com_baselinehq_golang_shared_types/vm.github_com_baselinehq_golang-shared_types.VM(
                    cpu_cores = 1.337, 
                    ram_gb = 1.337, )
            )
        else:
            return TypesComputeRequest(
        )
        """

    def testTypesComputeRequest(self):
        """Test TypesComputeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
