# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: support@costgraph.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricing_api_client.api.marketplace_api import MarketplaceApi


class TestMarketplaceApi(unittest.TestCase):
    """MarketplaceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MarketplaceApi()

    def tearDown(self) -> None:
        pass

    def test_v1_marketplace_compute_get(self) -> None:
        """Test case for v1_marketplace_compute_get

        List your compute prices
        """
        pass

    def test_v1_marketplace_compute_id_delete(self) -> None:
        """Test case for v1_marketplace_compute_id_delete

        Delete one compute price
        """
        pass

    def test_v1_marketplace_compute_id_get(self) -> None:
        """Test case for v1_marketplace_compute_id_get

        Read one compute price
        """
        pass

    def test_v1_marketplace_compute_id_patch(self) -> None:
        """Test case for v1_marketplace_compute_id_patch

        Change one compute price
        """
        pass

    def test_v1_marketplace_compute_post(self) -> None:
        """Test case for v1_marketplace_compute_post

        Publish compute prices
        """
        pass

    def test_v1_marketplace_databases_get(self) -> None:
        """Test case for v1_marketplace_databases_get

        List your database prices
        """
        pass

    def test_v1_marketplace_databases_id_delete(self) -> None:
        """Test case for v1_marketplace_databases_id_delete

        Delete one database price
        """
        pass

    def test_v1_marketplace_databases_id_get(self) -> None:
        """Test case for v1_marketplace_databases_id_get

        Read one database price
        """
        pass

    def test_v1_marketplace_databases_id_patch(self) -> None:
        """Test case for v1_marketplace_databases_id_patch

        Change one database price
        """
        pass

    def test_v1_marketplace_databases_post(self) -> None:
        """Test case for v1_marketplace_databases_post

        Publish database prices
        """
        pass

    def test_v1_marketplace_disks_get(self) -> None:
        """Test case for v1_marketplace_disks_get

        List your disk prices
        """
        pass

    def test_v1_marketplace_disks_id_delete(self) -> None:
        """Test case for v1_marketplace_disks_id_delete

        Delete one disk price
        """
        pass

    def test_v1_marketplace_disks_id_get(self) -> None:
        """Test case for v1_marketplace_disks_id_get

        Read one disk price
        """
        pass

    def test_v1_marketplace_disks_id_patch(self) -> None:
        """Test case for v1_marketplace_disks_id_patch

        Change one disk price
        """
        pass

    def test_v1_marketplace_disks_post(self) -> None:
        """Test case for v1_marketplace_disks_post

        Publish disk prices
        """
        pass

    def test_v1_marketplace_filters_kind_get(self) -> None:
        """Test case for v1_marketplace_filters_kind_get

        List the filters a price kind accepts
        """
        pass

    def test_v1_marketplace_models_get(self) -> None:
        """Test case for v1_marketplace_models_get

        List your model prices
        """
        pass

    def test_v1_marketplace_models_id_delete(self) -> None:
        """Test case for v1_marketplace_models_id_delete

        Delete one model price
        """
        pass

    def test_v1_marketplace_models_id_get(self) -> None:
        """Test case for v1_marketplace_models_id_get

        Read one model price
        """
        pass

    def test_v1_marketplace_models_id_patch(self) -> None:
        """Test case for v1_marketplace_models_id_patch

        Change one model price
        """
        pass

    def test_v1_marketplace_models_post(self) -> None:
        """Test case for v1_marketplace_models_post

        Publish model prices
        """
        pass


if __name__ == '__main__':
    unittest.main()
