# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: contact@baselinehq.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricing_api_client.models.types_predicates import TypesPredicates

class TestTypesPredicates(unittest.TestCase):
    """TypesPredicates unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TypesPredicates:
        """Test TypesPredicates
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TypesPredicates`
        """
        model = TypesPredicates()
        if include_optional:
            return TypesPredicates(
                availability_zones = [
                    ''
                    ],
                disk_types = [
                    ''
                    ],
                instance_types = [
                    ''
                    ],
                operating_systems = [
                    ''
                    ],
                providers = [
                    ''
                    ],
                regions = [
                    ''
                    ],
                services = [
                    ''
                    ],
                usage_types = [
                    ''
                    ]
            )
        else:
            return TypesPredicates(
        )
        """

    def testTypesPredicates(self):
        """Test TypesPredicates"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
