# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: contact@baselinehq.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricing_api_client.models.provider_config import ProviderConfig

class TestProviderConfig(unittest.TestCase):
    """ProviderConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProviderConfig:
        """Test ProviderConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProviderConfig`
        """
        model = ProviderConfig()
        if include_optional:
            return ProviderConfig(
                predicates = pricing_api_client.models.types/predicates.types.Predicates(
                    availability_zones = [
                        ''
                        ], 
                    disk_types = [
                        ''
                        ], 
                    instance_types = [
                        ''
                        ], 
                    operating_systems = [
                        ''
                        ], 
                    providers = [
                        ''
                        ], 
                    regions = [
                        ''
                        ], 
                    services = [
                        ''
                        ], 
                    usage_types = [
                        ''
                        ], ),
                provider = 'GCP'
            )
        else:
            return ProviderConfig(
        )
        """

    def testProviderConfig(self):
        """Test ProviderConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
