# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: contact@baselinehq.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricing_api_client.models.github_com_baselinehq_golang_shared_types_vm import GithubComBaselinehqGolangSharedTypesVM

class TestGithubComBaselinehqGolangSharedTypesVM(unittest.TestCase):
    """GithubComBaselinehqGolangSharedTypesVM unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GithubComBaselinehqGolangSharedTypesVM:
        """Test GithubComBaselinehqGolangSharedTypesVM
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GithubComBaselinehqGolangSharedTypesVM`
        """
        model = GithubComBaselinehqGolangSharedTypesVM()
        if include_optional:
            return GithubComBaselinehqGolangSharedTypesVM(
                cpu_cores = 1.337,
                ram_gb = 1.337
            )
        else:
            return GithubComBaselinehqGolangSharedTypesVM(
        )
        """

    def testGithubComBaselinehqGolangSharedTypesVM(self):
        """Test GithubComBaselinehqGolangSharedTypesVM"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
