# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: contact@baselinehq.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricing_api_client.models.types_custom_pricing_response import TypesCustomPricingResponse

class TestTypesCustomPricingResponse(unittest.TestCase):
    """TypesCustomPricingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TypesCustomPricingResponse:
        """Test TypesCustomPricingResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TypesCustomPricingResponse`
        """
        model = TypesCustomPricingResponse()
        if include_optional:
            return TypesCustomPricingResponse(
                entries = [
                    pricing_api_client.models.schema/compute_pricings_row.schema.ComputePricingsRow(
                        availability_zone = '', 
                        cost_per_hour = 1.337, 
                        cpu_cores = 1.337, 
                        cpu_cores_cost_per_hour = 1.337, 
                        created_at = '', 
                        id = '', 
                        instance_type = '', 
                        operating_system = '', 
                        period_billing_hours = 1.337, 
                        provider = '', 
                        ram_gb = 1.337, 
                        ram_gb_cost_per_hour = 1.337, 
                        raw_pricing_data = pricing_api_client.models.raw_pricing_data.raw_pricing_data(), 
                        region = '', 
                        service = '', 
                        tags = pricing_api_client.models.tags.tags(), 
                        updated_at = '', 
                        usage_type = '', )
                    ],
                status = 'Registered'
            )
        else:
            return TypesCustomPricingResponse(
        )
        """

    def testTypesCustomPricingResponse(self):
        """Test TypesCustomPricingResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
