# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: support@costgraph.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricing_api_client.models.compute_price import ComputePrice

class TestComputePrice(unittest.TestCase):
    """ComputePrice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ComputePrice:
        """Test ComputePrice
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ComputePrice`
        """
        model = ComputePrice()
        if include_optional:
            return ComputePrice(
                architecture = '',
                availability_zone = '',
                cost_per_hour = 1.337,
                cpu_cores = 1.337,
                cpu_cores_cost_per_hour = 1.337,
                created_at = '',
                currency = '',
                gpu_cost_per_hour = 1.337,
                gpu_count = 1.337,
                gpu_type = '',
                id = '',
                instance_type = '',
                native_cost_per_hour = 1.337,
                operating_system = '',
                period_billing_hours = 1.337,
                provider = '',
                ram_gb = 1.337,
                ram_gb_cost_per_hour = 1.337,
                raw_pricing_data = None,
                region = '',
                service = '',
                tags = None,
                updated_at = '',
                usage_type = ''
            )
        else:
            return ComputePrice(
        )
        """

    def testComputePrice(self):
        """Test ComputePrice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
