# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: contact@baselinehq.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricing_api_client.models.types_disk import TypesDisk

class TestTypesDisk(unittest.TestCase):
    """TypesDisk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TypesDisk:
        """Test TypesDisk
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TypesDisk`
        """
        model = TypesDisk()
        if include_optional:
            return TypesDisk(
                availability_zone = '',
                capacity_gb = 1.337,
                id = '',
                iops = 1.337,
                provider = 'GCP',
                region = '',
                service = 'ComputeEngine',
                throughput_mbps = 1.337,
                type = '',
                usage_type = 'SPOT_PREEMPTIBLE'
            )
        else:
            return TypesDisk(
        )
        """

    def testTypesDisk(self):
        """Test TypesDisk"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
