# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: support@costgraph.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DatabasePrice(BaseModel):
    """
    DatabasePrice
    """ # noqa: E501
    architecture: Optional[StrictStr] = None
    availability_zone: Optional[StrictStr] = None
    billing_config: Optional[StrictStr] = None
    capacity_unit: Optional[StrictStr] = None
    cost_per_capacity_unit: Optional[Union[StrictFloat, StrictInt]] = None
    cost_per_hour: Optional[Union[StrictFloat, StrictInt]] = None
    cost_per_io_request: Optional[Union[StrictFloat, StrictInt]] = None
    cost_per_iops_hour: Optional[Union[StrictFloat, StrictInt]] = None
    cost_per_storage_gb_hour: Optional[Union[StrictFloat, StrictInt]] = None
    cost_per_throughput_mbps_hour: Optional[Union[StrictFloat, StrictInt]] = None
    cost_per_vcpu_license_hour: Optional[Union[StrictFloat, StrictInt]] = None
    cpu_cores: Optional[Union[StrictFloat, StrictInt]] = None
    cpu_cores_cost_per_hour: Optional[Union[StrictFloat, StrictInt]] = None
    created_at: Optional[StrictStr] = None
    currency: Optional[StrictStr] = None
    deployment_option: Optional[StrictStr] = None
    edition: Optional[StrictStr] = None
    engine: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    instance_type: Optional[StrictStr] = None
    max_iops: Optional[Union[StrictFloat, StrictInt]] = None
    max_storage_gb: Optional[Union[StrictFloat, StrictInt]] = None
    max_throughput_mbps: Optional[Union[StrictFloat, StrictInt]] = None
    min_iops: Optional[Union[StrictFloat, StrictInt]] = None
    min_storage_gb: Optional[Union[StrictFloat, StrictInt]] = None
    min_throughput_mbps: Optional[Union[StrictFloat, StrictInt]] = None
    native_cost_per_hour: Optional[Union[StrictFloat, StrictInt]] = None
    native_cost_per_storage_gb_hour: Optional[Union[StrictFloat, StrictInt]] = None
    period_billing_hours: Optional[Union[StrictFloat, StrictInt]] = None
    provider: Optional[StrictStr] = None
    ram_gb: Optional[Union[StrictFloat, StrictInt]] = None
    ram_gb_cost_per_hour: Optional[Union[StrictFloat, StrictInt]] = None
    raw_pricing_data: Optional[Dict[str, Any]] = None
    region: Optional[StrictStr] = None
    service: Optional[StrictStr] = None
    storage_type: Optional[StrictStr] = None
    tags: Optional[Dict[str, Any]] = None
    updated_at: Optional[StrictStr] = None
    usage_type: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["architecture", "availability_zone", "billing_config", "capacity_unit", "cost_per_capacity_unit", "cost_per_hour", "cost_per_io_request", "cost_per_iops_hour", "cost_per_storage_gb_hour", "cost_per_throughput_mbps_hour", "cost_per_vcpu_license_hour", "cpu_cores", "cpu_cores_cost_per_hour", "created_at", "currency", "deployment_option", "edition", "engine", "id", "instance_type", "max_iops", "max_storage_gb", "max_throughput_mbps", "min_iops", "min_storage_gb", "min_throughput_mbps", "native_cost_per_hour", "native_cost_per_storage_gb_hour", "period_billing_hours", "provider", "ram_gb", "ram_gb_cost_per_hour", "raw_pricing_data", "region", "service", "storage_type", "tags", "updated_at", "usage_type"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DatabasePrice from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DatabasePrice from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "architecture": obj.get("architecture"),
            "availability_zone": obj.get("availability_zone"),
            "billing_config": obj.get("billing_config"),
            "capacity_unit": obj.get("capacity_unit"),
            "cost_per_capacity_unit": obj.get("cost_per_capacity_unit"),
            "cost_per_hour": obj.get("cost_per_hour"),
            "cost_per_io_request": obj.get("cost_per_io_request"),
            "cost_per_iops_hour": obj.get("cost_per_iops_hour"),
            "cost_per_storage_gb_hour": obj.get("cost_per_storage_gb_hour"),
            "cost_per_throughput_mbps_hour": obj.get("cost_per_throughput_mbps_hour"),
            "cost_per_vcpu_license_hour": obj.get("cost_per_vcpu_license_hour"),
            "cpu_cores": obj.get("cpu_cores"),
            "cpu_cores_cost_per_hour": obj.get("cpu_cores_cost_per_hour"),
            "created_at": obj.get("created_at"),
            "currency": obj.get("currency"),
            "deployment_option": obj.get("deployment_option"),
            "edition": obj.get("edition"),
            "engine": obj.get("engine"),
            "id": obj.get("id"),
            "instance_type": obj.get("instance_type"),
            "max_iops": obj.get("max_iops"),
            "max_storage_gb": obj.get("max_storage_gb"),
            "max_throughput_mbps": obj.get("max_throughput_mbps"),
            "min_iops": obj.get("min_iops"),
            "min_storage_gb": obj.get("min_storage_gb"),
            "min_throughput_mbps": obj.get("min_throughput_mbps"),
            "native_cost_per_hour": obj.get("native_cost_per_hour"),
            "native_cost_per_storage_gb_hour": obj.get("native_cost_per_storage_gb_hour"),
            "period_billing_hours": obj.get("period_billing_hours"),
            "provider": obj.get("provider"),
            "ram_gb": obj.get("ram_gb"),
            "ram_gb_cost_per_hour": obj.get("ram_gb_cost_per_hour"),
            "raw_pricing_data": obj.get("raw_pricing_data"),
            "region": obj.get("region"),
            "service": obj.get("service"),
            "storage_type": obj.get("storage_type"),
            "tags": obj.get("tags"),
            "updated_at": obj.get("updated_at"),
            "usage_type": obj.get("usage_type")
        })
        return _obj


