# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: contact@baselinehq.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class GithubComBaselinehqGolangSharedTypesService(str, Enum):
    """
    GithubComBaselinehqGolangSharedTypesService
    """

    """
    allowed enum values
    """
    ComputeEngine = 'ComputeEngine'
    AmazonEC2 = 'AmazonEC2'
    Droplet = 'Droplet'
    AzureCompute = 'AzureCompute'
    AzureManagedDisks = 'AzureManagedDisks'
    HetznerCompute = 'HetznerCompute'
    OVHPublicCloud = 'OVHPublicCloud'
    BaseCompute = 'BaseCompute'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GithubComBaselinehqGolangSharedTypesService from a JSON string"""
        return cls(json.loads(json_str))


