# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: contact@baselinehq.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class GithubComBaselinehqGolangSharedTypesUsageType(str, Enum):
    """
    GithubComBaselinehqGolangSharedTypesUsageType
    """

    """
    allowed enum values
    """
    SPOT_PREEMPTIBLE = 'SPOT_PREEMPTIBLE'
    ONDEMAND = 'ONDEMAND'
    RESERVED = 'RESERVED'
    ONDEMAND_CUSTOM = 'ONDEMAND_CUSTOM'
    SPOT_PREEMPTIBLE_CUSTOM = 'SPOT_PREEMPTIBLE_CUSTOM'
    RESERVED_CUSTOM = 'RESERVED_CUSTOM'
    SOLE_TENANCY = 'SOLE_TENANCY'
    CUSTOM = 'CUSTOM'
    EXTENDED = 'EXTENDED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GithubComBaselinehqGolangSharedTypesUsageType from a JSON string"""
        return cls(json.loads(json_str))


