# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: support@costgraph.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ModelPrice(BaseModel):
    """
    ModelPrice
    """ # noqa: E501
    context_limit: Optional[StrictInt] = None
    currency: Optional[StrictStr] = None
    effective_from: Optional[StrictStr] = None
    effective_to: Optional[StrictStr] = None
    fetched_at: Optional[StrictStr] = None
    host: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    modalities_input: Optional[List[StrictStr]] = None
    modalities_output: Optional[List[StrictStr]] = None
    model: Optional[StrictStr] = None
    model_id: Optional[StrictStr] = None
    open_weights: Optional[StrictBool] = None
    output_limit: Optional[StrictInt] = None
    provider: Optional[StrictStr] = None
    publisher: Optional[StrictStr] = None
    raw_pricing_data: Optional[Dict[str, Any]] = None
    reasoning: Optional[StrictBool] = None
    region: Optional[StrictStr] = None
    sku_price_id: Optional[StrictStr] = None
    source: Optional[StrictStr] = None
    source_url: Optional[StrictStr] = None
    structured_output: Optional[StrictBool] = None
    tags: Optional[Dict[str, Any]] = None
    token_bucket: Optional[StrictStr] = None
    tool_call: Optional[StrictBool] = None
    unit_price_per_mtok: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["context_limit", "currency", "effective_from", "effective_to", "fetched_at", "host", "id", "modalities_input", "modalities_output", "model", "model_id", "open_weights", "output_limit", "provider", "publisher", "raw_pricing_data", "reasoning", "region", "sku_price_id", "source", "source_url", "structured_output", "tags", "token_bucket", "tool_call", "unit_price_per_mtok"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModelPrice from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModelPrice from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "context_limit": obj.get("context_limit"),
            "currency": obj.get("currency"),
            "effective_from": obj.get("effective_from"),
            "effective_to": obj.get("effective_to"),
            "fetched_at": obj.get("fetched_at"),
            "host": obj.get("host"),
            "id": obj.get("id"),
            "modalities_input": obj.get("modalities_input"),
            "modalities_output": obj.get("modalities_output"),
            "model": obj.get("model"),
            "model_id": obj.get("model_id"),
            "open_weights": obj.get("open_weights"),
            "output_limit": obj.get("output_limit"),
            "provider": obj.get("provider"),
            "publisher": obj.get("publisher"),
            "raw_pricing_data": obj.get("raw_pricing_data"),
            "reasoning": obj.get("reasoning"),
            "region": obj.get("region"),
            "sku_price_id": obj.get("sku_price_id"),
            "source": obj.get("source"),
            "source_url": obj.get("source_url"),
            "structured_output": obj.get("structured_output"),
            "tags": obj.get("tags"),
            "token_bucket": obj.get("token_bucket"),
            "tool_call": obj.get("tool_call"),
            "unit_price_per_mtok": obj.get("unit_price_per_mtok")
        })
        return _obj


