# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: contact@baselinehq.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class SchemaComputePricingsRow(BaseModel):
    """
    SchemaComputePricingsRow
    """ # noqa: E501
    availability_zone: Optional[StrictStr] = None
    cost_per_hour: Optional[Union[StrictFloat, StrictInt]] = None
    cpu_cores: Optional[Union[StrictFloat, StrictInt]] = None
    cpu_cores_cost_per_hour: Optional[Union[StrictFloat, StrictInt]] = None
    created_at: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    instance_type: Optional[StrictStr] = None
    operating_system: Optional[StrictStr] = None
    period_billing_hours: Optional[Union[StrictFloat, StrictInt]] = None
    provider: Optional[StrictStr] = None
    ram_gb: Optional[Union[StrictFloat, StrictInt]] = None
    ram_gb_cost_per_hour: Optional[Union[StrictFloat, StrictInt]] = None
    raw_pricing_data: Optional[Dict[str, Any]] = None
    region: Optional[StrictStr] = None
    service: Optional[StrictStr] = None
    tags: Optional[Dict[str, Any]] = None
    updated_at: Optional[StrictStr] = None
    usage_type: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["availability_zone", "cost_per_hour", "cpu_cores", "cpu_cores_cost_per_hour", "created_at", "id", "instance_type", "operating_system", "period_billing_hours", "provider", "ram_gb", "ram_gb_cost_per_hour", "raw_pricing_data", "region", "service", "tags", "updated_at", "usage_type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SchemaComputePricingsRow from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SchemaComputePricingsRow from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "availability_zone": obj.get("availability_zone"),
            "cost_per_hour": obj.get("cost_per_hour"),
            "cpu_cores": obj.get("cpu_cores"),
            "cpu_cores_cost_per_hour": obj.get("cpu_cores_cost_per_hour"),
            "created_at": obj.get("created_at"),
            "id": obj.get("id"),
            "instance_type": obj.get("instance_type"),
            "operating_system": obj.get("operating_system"),
            "period_billing_hours": obj.get("period_billing_hours"),
            "provider": obj.get("provider"),
            "ram_gb": obj.get("ram_gb"),
            "ram_gb_cost_per_hour": obj.get("ram_gb_cost_per_hour"),
            "raw_pricing_data": obj.get("raw_pricing_data"),
            "region": obj.get("region"),
            "service": obj.get("service"),
            "tags": obj.get("tags"),
            "updated_at": obj.get("updated_at"),
            "usage_type": obj.get("usage_type")
        })
        return _obj


