# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: contact@baselinehq.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TypesPredicates(BaseModel):
    """
    TypesPredicates
    """ # noqa: E501
    availability_zones: Optional[List[StrictStr]] = None
    disk_types: Optional[List[StrictStr]] = None
    instance_types: Optional[List[StrictStr]] = None
    operating_systems: Optional[List[StrictStr]] = None
    providers: Optional[List[StrictStr]] = None
    regions: Optional[List[StrictStr]] = None
    services: Optional[List[StrictStr]] = None
    usage_types: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["availability_zones", "disk_types", "instance_types", "operating_systems", "providers", "regions", "services", "usage_types"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TypesPredicates from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TypesPredicates from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "availability_zones": obj.get("availability_zones"),
            "disk_types": obj.get("disk_types"),
            "instance_types": obj.get("instance_types"),
            "operating_systems": obj.get("operating_systems"),
            "providers": obj.get("providers"),
            "regions": obj.get("regions"),
            "services": obj.get("services"),
            "usage_types": obj.get("usage_types")
        })
        return _obj


