# coding: utf-8

"""
    Pricing API

    Provides API level access to the Costgraph Services.

    The version of the OpenAPI document: 1.0
    Contact: contact@baselinehq.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from pricing_api_client.models.github_com_baselinehq_golang_shared_types_provider import GithubComBaselinehqGolangSharedTypesProvider
from pricing_api_client.models.github_com_baselinehq_golang_shared_types_service import GithubComBaselinehqGolangSharedTypesService
from pricing_api_client.models.github_com_baselinehq_golang_shared_types_usage_type import GithubComBaselinehqGolangSharedTypesUsageType
from typing import Optional, Set
from typing_extensions import Self

class TypesDisk(BaseModel):
    """
    TypesDisk
    """ # noqa: E501
    availability_zone: Optional[StrictStr] = None
    capacity_gb: Optional[Union[StrictFloat, StrictInt]] = None
    id: Optional[StrictStr] = None
    iops: Optional[Union[StrictFloat, StrictInt]] = None
    provider: Optional[GithubComBaselinehqGolangSharedTypesProvider] = None
    region: Optional[StrictStr] = None
    service: Optional[GithubComBaselinehqGolangSharedTypesService] = None
    throughput_mbps: Optional[Union[StrictFloat, StrictInt]] = None
    type: Optional[StrictStr] = None
    usage_type: Optional[GithubComBaselinehqGolangSharedTypesUsageType] = None
    __properties: ClassVar[List[str]] = ["availability_zone", "capacity_gb", "id", "iops", "provider", "region", "service", "throughput_mbps", "type", "usage_type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TypesDisk from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TypesDisk from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "availability_zone": obj.get("availability_zone"),
            "capacity_gb": obj.get("capacity_gb"),
            "id": obj.get("id"),
            "iops": obj.get("iops"),
            "provider": obj.get("provider"),
            "region": obj.get("region"),
            "service": obj.get("service"),
            "throughput_mbps": obj.get("throughput_mbps"),
            "type": obj.get("type"),
            "usage_type": obj.get("usage_type")
        })
        return _obj


